<a href="https://colab.research.google.com/github/SSRangari/Exploratory_Data_Analysis_project/blob/main/Online%20Payment%20Fraud%20Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Project Title: Online Payments Fraud Detection Dataset
About Dataset
1. step: represents a unit of time where 1 step equals 1 hour
2. type: type of online transaction
3. amount: the amount of the transaction
4. nameOrig: customer starting the transaction
5. oldbalanceOrg: balance before the transaction
6. newbalanceOrig: balance after the transaction
7. nameDest: recipient of the transaction
8. oldbalanceDest: initial balance of recipient before the transaction
9. newbalanceDest: the new balance of recipient after the transaction
10. isFraud: fraud transaction
Steps to Perform:
Follow the CRISP – DM methodology to reach the end solution

In [1]:
import pandas as pd
import numpy as np
import copy
import plotly.express as px
import seaborn as sns
%matplotlib
from sklearn.model_selection import train_test_split

Using matplotlib backend: agg


In [2]:
data = pd.read_csv(input("Enter path:-"))

Enter path:-/content/payment fraud detection.csv


In [3]:
data.head()

step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815       170136.0       160296.36   
1     1   PAYMENT   1864.28  C1666544295        21249.0        19384.72   
2     1  TRANSFER    181.00  C1305486145          181.0            0.00   
3     1  CASH_OUT    181.00   C840083671          181.0            0.00   
4     1   PAYMENT  11668.14  C2048537720        41554.0        29885.86   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0  M1979787155             0.0             0.0      0.0             0.0  
1  M2044282225             0.0             0.0      0.0             0.0  
2   C553264065             0.0             0.0      1.0             0.0  
3    C38997010         21182.0             0.0      1.0             0.0  
4  M1230701703             0.0             0.0      0.0             0.0

In [4]:
def data_understand(data):
    print("\n","Name of the columns",data.columns)
    #lets check out the name of collumns
    print("\n","size of the detaset",data.shape)
      #lets check out the no. of size of detaset
    print("\n","understaning the detaset information",data.info())
      # understanding info
    return data.isnull().sum()
       # lets check missing values in dataset

In [5]:
data_understand(data)


 Name of the columns Index(['step', 'type', 'amount', 'nameOrig', 'oldbalanceOrg', 'newbalanceOrig',
       'nameDest', 'oldbalanceDest', 'newbalanceDest', 'isFraud',
       'isFlaggedFraud'],
      dtype='object')

 size of the detaset (28297, 11)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28297 entries, 0 to 28296
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   step            28297 non-null  int64  
 1   type            28297 non-null  object 
 2   amount          28297 non-null  float64
 3   nameOrig        28297 non-null  object 
 4   oldbalanceOrg   28297 non-null  float64
 5   newbalanceOrig  28297 non-null  float64
 6   nameDest        28297 non-null  object 
 7   oldbalanceDest  28297 non-null  float64
 8   newbalanceDest  28297 non-null  float64
 9   isFraud         28296 non-null  float64
 10  isFlaggedFraud  28296 non-null  float64
dtypes: float64(7), int64(1), object(3)
memory usage: 2.

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           1
isFlaggedFraud    1
dtype: int64

In [6]:
data.shape

(28297, 11)

In [7]:
data['isFraud'].value_counts()

0.0    28212
1.0       84
Name: isFraud, dtype: int64

In [8]:
# this dataset are so unbalence

In [9]:
data=data.dropna()

In [10]:
data['nameDest'].unique()

array(['M1979787155', 'M2044282225', 'C553264065', ..., 'M301121578',
       'M1505232216', 'C345691183'], dtype=object)

In [11]:
data['nameOrig'].unique()

array(['C1231006815', 'C1666544295', 'C1305486145', ..., 'C1845952463',
       'C140193335', 'C297851161'], dtype=object)

In [12]:
data['type'].unique()

array(['PAYMENT', 'TRANSFER', 'CASH_OUT', 'DEBIT', 'CASH_IN'],
      dtype=object)

In [13]:
data.drop(["nameOrig","nameDest"], axis=1 , inplace=True)

In [14]:
##convert non numeric to numeric

 
data = pd.get_dummies(data, columns=['type'])


In [15]:
data.head()

step    amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0     1   9839.64       170136.0       160296.36             0.0   
1     1   1864.28        21249.0        19384.72             0.0   
2     1    181.00          181.0            0.00             0.0   
3     1    181.00          181.0            0.00         21182.0   
4     1  11668.14        41554.0        29885.86             0.0   

   newbalanceDest  isFraud  isFlaggedFraud  type_CASH_IN  type_CASH_OUT  \
0             0.0      0.0             0.0             0              0   
1             0.0      0.0             0.0             0              0   
2             0.0      1.0             0.0             0              0   
3             0.0      1.0             0.0             0              1   
4             0.0      0.0             0.0             0              0   

   type_DEBIT  type_PAYMENT  type_TRANSFER  
0           0             1              0  
1           0             1              0  
2           0             0              1  
3           0             0              0  
4           0             1              0

In [16]:

data.describe().transpose()

count          mean           std   min        25%  \
step            28296.0  6.508199e+00  2.291113e+00  1.00     6.0000   
amount          28296.0  1.357431e+05  3.013217e+05  1.77  5966.4625   
oldbalanceOrg   28296.0  7.667297e+05  2.126156e+06  0.00     0.0000   
newbalanceOrig  28296.0  7.823827e+05  2.166648e+06  0.00     0.0000   
oldbalanceDest  28296.0  8.484026e+05  2.513911e+06  0.00     0.0000   
newbalanceDest  28296.0  1.191347e+06  3.106488e+06  0.00     0.0000   
isFraud         28296.0  2.968617e-03  5.440505e-02  0.00     0.0000   
isFlaggedFraud  28296.0  0.000000e+00  0.000000e+00  0.00     0.0000   
type_CASH_IN    28296.0  1.776576e-01  3.822310e-01  0.00     0.0000   
type_CASH_OUT   28296.0  2.158609e-01  4.114255e-01  0.00     0.0000   
type_DEBIT      28296.0  1.812977e-02  1.334231e-01  0.00     0.0000   
type_PAYMENT    28296.0  4.916949e-01  4.999399e-01  0.00     0.0000   
type_TRANSFER   28296.0  9.665677e-02  2.954951e-01  0.00     0.0000   

                      50%          75%          max  
step                8.000       8.0000         8.00  
amount          19501.960  160111.7525  10000000.00  
oldbalanceOrg   19647.270  138688.9100  22352310.12  
newbalanceOrig   3685.915  140767.3500  22465998.18  
oldbalanceDest      0.000  365572.1400  24955238.07  
newbalanceDest      0.000  667597.9600  28783585.38  
isFraud             0.000       0.0000         1.00  
isFlaggedFraud      0.000       0.0000         0.00  
type_CASH_IN        0.000       0.0000         1.00  
type_CASH_OUT       0.000       0.0000         1.00  
type_DEBIT          0.000       0.0000         1.00  
type_PAYMENT        0.000       1.0000         1.00  
type_TRANSFER       0.000       0.0000         1.00

In [17]:
X = data.drop('isFraud',axis=1)

                                                                    
Y = data['isFraud']

In [18]:
X.head()

step    amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0     1   9839.64       170136.0       160296.36             0.0   
1     1   1864.28        21249.0        19384.72             0.0   
2     1    181.00          181.0            0.00             0.0   
3     1    181.00          181.0            0.00         21182.0   
4     1  11668.14        41554.0        29885.86             0.0   

   newbalanceDest  isFlaggedFraud  type_CASH_IN  type_CASH_OUT  type_DEBIT  \
0             0.0             0.0             0              0           0   
1             0.0             0.0             0              0           0   
2             0.0             0.0             0              0           0   
3             0.0             0.0             0              1           0   
4             0.0             0.0             0              0           0   

   type_PAYMENT  type_TRANSFER  
0             1              0  
1             1              0  
2             0              1  
3             0              0  
4             1              0

In [19]:
Y.head()

0    0.0
1    0.0
2    1.0
3    1.0
4    0.0
Name: isFraud, dtype: float64

In [20]:
for i in X.columns:
    fig=px.box(X,y=i, width=600, height=400, title=i, template="plotly_dark")
    fig.show()

In [21]:
feature_columns = X.columns

for i in feature_columns:
    X[i] = np.where(X[i] > (X[i].quantile(0.75) + (X[i].quantile(0.75) - X[i].quantile(0.25))*1.5),
                           (X[i].quantile(0.75) + (X[i].quantile(0.75) - X[i].quantile(0.25))*1.5),
                          np.where(X[i] < (X[i].quantile(0.25) - (X[i].quantile(0.75) - X[i].quantile(0.25))*1.5),
                           (X[i].quantile(0.25) - (X[i].quantile(0.75) - X[i].quantile(0.25))*1.5),X[i]))


In [22]:
#combaine target and independent variable
samp = pd.concat([X,Y],axis=1)

In [23]:
samp.head()

step    amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
0   3.0   9839.64       170136.0       160296.36             0.0   
1   3.0   1864.28        21249.0        19384.72             0.0   
2   3.0    181.00          181.0            0.00             0.0   
3   3.0    181.00          181.0            0.00         21182.0   
4   3.0  11668.14        41554.0        29885.86             0.0   

   newbalanceDest  isFlaggedFraud  type_CASH_IN  type_CASH_OUT  type_DEBIT  \
0             0.0             0.0           0.0            0.0         0.0   
1             0.0             0.0           0.0            0.0         0.0   
2             0.0             0.0           0.0            0.0         0.0   
3             0.0             0.0           0.0            0.0         0.0   
4             0.0             0.0           0.0            0.0         0.0   

   type_PAYMENT  type_TRANSFER  isFraud  
0           1.0            0.0      0.0  
1           1.0            0.0      0.0  
2           0.0            0.0      1.0  
3           0.0            0.0      1.0  
4           1.0            0.0      0.0

In [24]:
import matplotlib.pyplot as plt

In [63]:

sns.pairplot(samp)  #pairplot
plt.show()



In [26]:

fig, ax = plt.subplots(figsize=(50,30)) 


sns.heatmap(samp.corr(method = "pearson"), annot = True, cmap="YlGnBu", linewidths=.5, ax=ax)

In [27]:
samp.drop(["isFlaggedFraud"], axis=1 , inplace=True)

In [28]:
X1 = samp.drop('isFraud',axis=1)

                                                                    
Y1 = samp['isFraud']

In [29]:
X_train,X_test,y_train,y_test=train_test_split(X1,Y1,test_size=0.3,random_state=7)

In [30]:
## Import Libraries

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [31]:
model = KNeighborsClassifier()

##model.get_params()

In [32]:
## benchmark model


scale = MinMaxScaler()

train_scale = scale.fit_transform(X_train)
test_scale = scale.transform(X_test)

model.fit(train_scale, y_train)

y_pred = model.predict(test_scale)

print(accuracy_score(y_test, y_pred))


## Confusion Matrix

print(confusion_matrix(y_test, y_pred, labels = [0,1]))

print(classification_report(y_test, y_pred))

0.9977618094004005
[[8458    6]
 [  13   12]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      8464
         1.0       0.67      0.48      0.56        25

    accuracy                           1.00      8489
   macro avg       0.83      0.74      0.78      8489
weighted avg       1.00      1.00      1.00      8489



In [33]:
from sklearn.linear_model import LogisticRegression



In [34]:


##default solver method ('sag') ##scale data use sag and saga becouse of gd
logit_model = LogisticRegression()

logit_model.fit(train_scale, y_train)

y_pred = logit_model.predict(test_scale)

print(accuracy_score(y_test, y_pred))


## Confusion Matrix

print(confusion_matrix(y_test, y_pred, labels = [0,1]))

print(classification_report(y_test, y_pred))

0.9972906113794322
[[8464    0]
 [  23    2]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      8464
         1.0       1.00      0.08      0.15        25

    accuracy                           1.00      8489
   macro avg       1.00      0.54      0.57      8489
weighted avg       1.00      1.00      1.00      8489



In [35]:
from sklearn.svm import SVC

In [36]:
## SVM with default kernel trick ('rbf')
svm_model = SVC()

svm_model.fit(train_scale, y_train)

y_pred = svm_model.predict(test_scale)

print(accuracy_score(y_test, y_pred))


## Confusion Matrix

print(confusion_matrix(y_test, y_pred, labels = [0,1]))

print(classification_report(y_test, y_pred))

0.997055012368948
[[8464    0]
 [  25    0]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      8464
         1.0       0.00      0.00      0.00        25

    accuracy                           1.00      8489
   macro avg       0.50      0.50      0.50      8489
weighted avg       0.99      1.00      1.00      8489



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



In [37]:
from sklearn.ensemble import RandomForestClassifier  


In [38]:
#Befor sampling method
classifier= RandomForestClassifier(n_estimators= 100, criterion="entropy")## no use scale data

classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

print(accuracy_score(y_test, y_pred))


## Confusion Matrix

print(confusion_matrix(y_test, y_pred, labels = [0,1]))

print(classification_report(y_test, y_pred))

0.9982330074213688
[[8463    1]
 [  14   11]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      8464
         1.0       0.92      0.44      0.59        25

    accuracy                           1.00      8489
   macro avg       0.96      0.72      0.80      8489
weighted avg       1.00      1.00      1.00      8489



In [39]:
from sklearn.model_selection import KFold

from sklearn.model_selection import cross_val_score
from imblearn.over_sampling import SMOTE

In [40]:
# over sampling method to reduce the insamble of the data
sm = SMOTE(sampling_strategy = 1 ,k_neighbors = 5, random_state=1)   #Synthetic Minority Over Sampling Technique
X_train_res, y_train_res = sm.fit_resample(X_train, y_train.ravel())

In [41]:
print("Before overSampling, counts of label '1': {}".format(sum(y_train==1)))
print("Before overSampling, counts of label '0': {} \n".format(sum(y_train==0)))

Before overSampling, counts of label '1': 59
Before overSampling, counts of label '0': 19748 



In [42]:

print("After overSampling, counts of label '1': {}".format(sum(y_train_res==1)))
print("After overSampling, counts of label '0': {} \n".format(sum(y_train_res==0)))

After overSampling, counts of label '1': 19748
After overSampling, counts of label '0': 19748 



In [43]:
# use sampling method
classifier.fit(X_train_res, y_train_res)

y_pred = classifier.predict(X_test)

print(accuracy_score(y_test, y_pred))


## Confusion Matrix

print(confusion_matrix(y_test, y_pred, labels = [0,1]))

print(classification_report(y_test, y_pred))


cv_score_11 = cross_val_score(classifier , X_train_res, y_train_res, scoring = 'recall_macro', 
                                          cv = KFold(n_splits = 10))

cv_score_11.mean()

0.9981152079161267
[[8458    6]
 [  10   15]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      8464
         1.0       0.71      0.60      0.65        25

    accuracy                           1.00      8489
   macro avg       0.86      0.80      0.83      8489
weighted avg       1.00      1.00      1.00      8489



0.9858164560779127

In [44]:
from sklearn.model_selection import RandomizedSearchCV

In [45]:
# haper tunning parameter
n_estimators = [int(x) for x in np.linspace(start = 1, stop = 20, num = 20)]
max_features = ['auto', 'sqrt']
max_depth = [int(x) for x in np.linspace(10, 120, num = 12)]
min_samples_split = [2, 6, 10]
min_samples_leaf = [1, 3, 4]
bootstrap = [True, False]


random_grid = {'n_estimators': n_estimators,

'max_features': max_features,

'max_depth': max_depth,

'min_samples_split': min_samples_split,

'min_samples_leaf': min_samples_leaf,

'bootstrap': bootstrap}

In [46]:
# run randomized search

samples = 10                                                                              # number of random samples

randomCV = RandomizedSearchCV(classifier, 
                              param_distributions = random_grid, 
                              n_iter = samples, 
                              cv = 10)                                                    #default cv = 10

In [47]:
randomCV.fit(X_train_res, y_train_res)

 
print(randomCV.best_params_)

{'n_estimators': 6, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 110, 'bootstrap': False}


In [48]:
# use best parameter
final_rf = RandomForestClassifier(bootstrap = False, 
                                   
                                  max_depth = 70, 
                                  max_features ='sqrt', 
                                  min_samples_leaf = 1, 
                                  min_samples_split = 2,
                                  n_estimators=14)
final_rf.fit(X_train_res, y_train_res)

y_pred = final_rf.predict(X_test)

print(accuracy_score(y_test, y_pred))

## Confusion Matrix

print(confusion_matrix(y_test, y_pred, labels = [0,1]))

print(classification_report(y_test, y_pred))



0.9978796089056426
[[8457    7]
 [  11   14]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      8464
         1.0       0.67      0.56      0.61        25

    accuracy                           1.00      8489
   macro avg       0.83      0.78      0.80      8489
weighted avg       1.00      1.00      1.00      8489



In [49]:
# use cross validation for consistancy of model
final_rf.fit(X_train_res, y_train_res)

cv_score_rf = cross_val_score(final_rf , X_train_res, y_train_res, scoring = 'recall_macro', 
                                          cv = KFold(n_splits = 10))

In [50]:
cv_score_rf.mean()

0.9858292076754707

In [51]:
import xgboost as xgb

In [52]:
#Befor using sampling method
modelxg = xgb.XGBClassifier(random_state = 1)## scale data not use in trees

modelxg.fit(X_train, y_train)

y_pred = modelxg.predict(X_test)

print(accuracy_score(y_test, y_pred))

## Confusion Matrix

print(confusion_matrix(y_test, y_pred, labels = [0,1]))

print(classification_report(y_test, y_pred))


0.998468606431853
[[8463    1]
 [  12   13]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      8464
         1.0       0.93      0.52      0.67        25

    accuracy                           1.00      8489
   macro avg       0.96      0.76      0.83      8489
weighted avg       1.00      1.00      1.00      8489



In [53]:
#Used sampling method
modelxg = xgb.XGBClassifier(random_state = 1)

modelxg.fit(X_train_res, y_train_res)

y_pred = modelxg.predict(X_test)

print(accuracy_score(y_test, y_pred))

## Confusion Matrix

print(confusion_matrix(y_test, y_pred, labels = [0,1]))

print(classification_report(y_test, y_pred))


0.992460831664507
[[8401   63]
 [   1   24]]
              precision    recall  f1-score   support

         0.0       1.00      0.99      1.00      8464
         1.0       0.28      0.96      0.43        25

    accuracy                           0.99      8489
   macro avg       0.64      0.98      0.71      8489
weighted avg       1.00      0.99      0.99      8489



In [54]:
# Hypertunning parameter
learning_rate= [0.05,0.10,0.15,0.20,0.25,0.30]
max_depth=[ 3, 4, 5, 6, 8, 10, 12, 15]
min_child_weight=[ 1, 3, 5, 7 ]
gamma =[ 0.0, 0.1, 0.2 , 0.3, 0.4 ]
colsample_bytree=[ 0.3, 0.4, 0.5 , 0.7 ]
random_grid = {

 'learning_rate': learning_rate,

  'max_depth': max_depth,

  'min_child_weight': min_child_weight,

  'gamma': gamma,

   'colsample_bytree':colsample_bytree
}   

In [55]:
# run randomized search
samples = 10                                                                              # number of random samples

randomCV1 = RandomizedSearchCV(modelxg, 
                              param_distributions = random_grid, 
                              n_iter = samples, 
                              cv = 10)                                                    #default cv = 10

In [56]:

randomCV1.fit(X_train_res, y_train_res)

 
print(randomCV1.best_params_)

{'min_child_weight': 1, 'max_depth': 10, 'learning_rate': 0.2, 'gamma': 0.1, 'colsample_bytree': 0.4}


In [58]:
# used best parameter
final_xg = xgb.XGBClassifier(bootstrap = False, 
                                   
                                  max_depth = 10, 
                                  min_child_weight= 1 ,
                                  learning_rate=0.2 ,
                                  gamma= 0.1,
                                 colsample_bytree= 0.4)
final_xg.fit(X_train_res, y_train_res)

y_pred = final_xg.predict(X_test)

print(accuracy_score(y_test, y_pred))

## Confusion Matrix

print(confusion_matrix(y_test, y_pred, labels = [0,1]))

print(classification_report(y_test, y_pred))


0.9981152079161267
[[8456    8]
 [   8   17]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      8464
         1.0       0.68      0.68      0.68        25

    accuracy                           1.00      8489
   macro avg       0.84      0.84      0.84      8489
weighted avg       1.00      1.00      1.00      8489



In [59]:
#use cross validation for check consistancy of model

final_xg.fit(X_train_res, y_train_res)

cv_score_xg = cross_val_score(final_xg , X_train_res, y_train_res, scoring = 'recall_macro', 
                                          cv = KFold(n_splits = 10))


In [60]:
cv_score_xg.mean()

0.9896879230275362

In [61]:
# for compair Random Forest and xgboost model so xgboost gives batter result so we can usexgboost

In [62]:
classifier.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'entropy',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}